config/routes.rb
Rails.application.routes.draw do
  get 'suggest', to: 'search#suggest'
  get 'search',  to: 'search#index'
  root to: 'names#index'
  resources :names
  post 'do_it', to: 'names#do_it'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/name.rb
class Name
  include Elasticsearch::Persistence::Model

  index_name :name

  analyzed_and_raw = { fields: {
      name: { type: 'text' },
      raw:  { type: 'keyword' }
  } }
  attribute :name, String, mapping: analyzed_and_raw

  attribute :states, String, default: []
  attribute :genders, String, default: []
  attribute :origins, String, default: []
  attribute :meaning, String, default: ''
  attribute :total_occurence, Integer
  attribute :first_seen_year, Integer
  attribute :first_seen_year, Integer

  # TODO
  # attribute :years_and_occurences, Hashie::Mash, mapping: {
  #   type: 'object',
  #   properties: {
  #       year: {type: Integer},
  #       occurence: {type: Integer}
  #   }
  # }

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  # before_action :set_name, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :do_it

  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end

  def index
    @from = params[:from].to_i
    @names = Name.all sort: 'name.raw', size: 1000, from: @from
  end

  def do_it
    client     = Name.gateway.client
    index_name = Name.index_name

    client.indices.delete index: index_name rescue nil

    settings = Name.settings.to_hash.merge(Name.settings.to_hash)
    mappings = Name.mappings.to_hash.merge(Name.mappings.to_hash)

    client.indices.create index: index_name,
                          body: {
                              settings: settings.to_hash,
                              mappings: mappings.to_hash }

    names = {}
    Dir.glob(File.join(File.dirname(__FILE__), '../../data/names_by_state', "*.TXT")).each do |file_name|
      puts file_name
      File.open(file_name).each_line do |line|
        state,gender,year,name,occurence = line.strip.split(",")
        year = year.to_i
        occurence = occurence.to_i
        gender = gender == 'F' ? 'Female' : 'Male'
        # TODO
        next if gender == 'Male'
        names[name] ||= {states: [],
                         genders: [],
                         origins: [],
                         # years_and_occurences:{},
                         total_occurence: 0,
                         first_seen_year: 2017,
                         last_seen_year: 1900}
        names[name][:states] << state unless names[name][:states].include?(state)
        names[name][:genders] << gender unless names[name][:genders].include?(gender)
        # names[name][:years_and_occurences][year] ||= 0
        # names[name][:years_and_occurences][year] = names[name][:years_and_occurences][year] + occurence.to_i
        names[name][:first_seen_year] = year < names[name][:first_seen_year] ? year : names[name][:first_seen_year]
        names[name][:last_seen_year] = year > names[name][:last_seen_year] ? year : names[name][:last_seen_year]
        names[name][:total_occurence] = names[name][:total_occurence] + occurence.to_i
      end
      puts "finished #{file_name}"
    end
    Dir.glob(File.join(File.dirname(__FILE__), '../../data/names_by_country', "*.txt")).each do |file_name|
      puts file_name
      File.open(file_name).each_line do |line|
        name = line.strip
        origin = file_name.strip.split('.')[2].split('/').last
        next unless names[name]
        names[name][:origins] << origin unless names[name][:origins].include?(origin)
      end
      puts "finished #{file_name}"
    end

    File.open(File.join(File.dirname(__FILE__), '../../data/names_by_letter/all_names.csv')).each_line do |line|
      name,gender,origin,meaning = line.strip.split("|")
      origins = origin.split(',').map{|o| o.strip}
      name = name.strip.capitalize
      next unless names[name]
      origins.each do |origin|
        names[name][:origins] << origin unless names[name][:origins].include?(origin)
      end
      names[name][:meaning] = meaning
    end

    File.open(File.join(File.dirname(__FILE__), '../../data/names_by_meaning/all_names.csv')).each_line do |line|
      puts line
      name,origin,meaning, other_names = line.strip.split("|")
      other_names = other_names ? other_names.split(',').map{|o| o.strip} : []
      other_names << name
      origins = origin.split(',').map{|o| o.strip}
      other_names.each do |name|
        next unless names[name]
        origins.each do |origin|
          names[name][:origins] << origin unless names[name][:origins].include?(origin)
        end
        names[name][:meaning] = meaning
      end
    end

    names.each do |name, name_hash|
      name_hash.update(id: name, name: name)
      Name.create name_hash, id: name_hash[:id]
    end; nil
  end
  # 
  # def new
  #   @name = Name.new
  # end
  # 
  # def edit
  # end
  # 
  # def create
  #   @name = Name.new(name_params)
  # 
  #   respond_to do |format|
  #     if @name.save refresh: true
  #       format.html { redirect_to @name, notice: 'Name was successfully created.' }
  #       format.json { render :show, status: :created, location: @name }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @name.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # def update
  #   respond_to do |format|
  #     if @name.update(name_params, refresh: true)
  #       format.html { redirect_to @name, notice: 'Name was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @name }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @name.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # def destroy
  #   @name.destroy refresh: true
  #   respond_to do |format|
  #     format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  # 
  # private
  #   def set_name
  #     @name = Name.find(params[:id].split('-').first)
  #   end
  # 
  #   def name_params
  #     a = params.require(:name)
  #     a[:members] = a[:members].split(/,\s?/) unless a[:members].is_a?(Array) || a[:members].blank?
  #     return a
  #   end
end

app/views/names/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name %>
  <%= f.input :profile, as: :text %>
  <%= f.input :date, as: :date %>
  <%= f.input :members, hint: 'Separate names by comma', input_html: { value: f.object.members.join(', ') } %>

  <%= f.button :submit %>
<% end %>

app/views/names/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/names/index.html.erb
<header>
  <h1>
    Names
    <%= button_to 'New Name', new_name_path, method: 'get', tabindex: 5 %>
  </h1>
</header>

<section>
<% if @from > 0 %>
    <%= link_to 'Previous Page', names_path(from: @from - 1000) %>
<% end %>
<% if @from < 20000 %>
  <%= link_to 'Next Page', names_path(from: @from + 1000) %>
<% end %>
</section>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="names">
  <% @names.each do |name| %>
    <%= div_for name, class: 'result clearfix' do %>
      <h2>
        <span class="name"><%= name.name %></span>
        <small><strong><%= name.origins.join(', ') %></strong></small>
        <small><strong><%= name.total_occurence %></strong></small>
        <small><strong><%= name.meaning %></strong></small>
      </h2>
    <% end %>
  <% end %>
</section>

<% if @names.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>
<section>
  <% if @from > 0 %>
      <%= link_to 'Previous Page', names_path(from: @from - 1000) %>
  <% end %>
  <% if @from < 20000 %>
      <%= link_to 'Next Page', names_path(from: @from + 1000) %>
  <% end %>
</section>


<script>
$.widget( "custom.suggest", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      $.each( items, function( index, item ) {
        var category = ul.append( "<li class='ui-autocomplete-category'>" + item.label + "</li>" );

        $.each( item.value, function( index, item ) {
          var li = $('<li class="ui-autocomplete-item"><a href="<%= Rails.application.config.relative_url_root %>'+ item.url +'">'+ item.text +'</a></li>').data('ui-autocomplete-item', item )
          category.append(li)
        } )
      });
    }
  });

$( "#q" ).suggest({
  source: '<%= suggest_path %>',
  select: function(event, ui) {
    document.location.href = '<%= Rails.application.config.relative_url_root %>'+ui.item.url
  }
});
</script>

<script>$('img.band').error(function(){ $(this).attr('src', '/images/blank_name.png'); });</script>

app/views/names/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/names/show.html.erb
<div class="artist">
  <header>
    <h1>
      <span class="back"><%= link_to "〈".html_safe, artists_path, title: "Back" %></span>
      <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/bands/#{@artist.id}.jpeg", height: '50px', class: 'band' %>
      <%= @artist.name %>
      <%= button_to 'Edit', edit_artist_path(@artist), method: 'get' %>
    </h1>
  </header>

  <p id="notice"><%= notice %></p>

  <section class="artist-info">
    <span><%= @artist.members.to_sentence last_word_connector: ' and ' %></span> |
    <span><%= pluralize @albums.size, 'album' %></span>
    <p class="artist-profile"><%= @artist.profile %></p>
  </section>

  <section class="albums">
    <% @albums.each do |album| %>
    <%= div_for album, class: 'clearfix' do %>
        <h3>
          <span class="title"><%= album.title %></span>
          <div class="info">
            <small><%= album.meta.formats.join(', ') %></small>
            <small><%= album.released %></small>
          </div>
        </h3>

        <div class="cover">
          <%= image_tag "http://ruby.elastic.co.s3-website-us-east-1.amazonaws.com/demo/music/covers/#{album.id}.jpeg", width: '100px', class: 'cover' %>
        </div>

        <div class="content">
          <% album.tracklist.in_groups_of(album.tracklist.size/2+1).each_with_index do |half, g| %>
            <ul class=<%= cycle 'first', 'second' %> start="<%= g < 1 ? 1 : album.tracklist.size/2+2 %>">
              <% half.compact.each_with_index do |track, i| %>
                <li>
                  <i class="counter"><%= g < 1 ? i+1 : i+(g*album.tracklist.size/2+2)  %></i>
                  <%= track['title'] %>
                  <small><%= track['duration'] %></small>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      <% end %>

    <% end %>

    <script>$('img').error(function(){ $(this).attr('src', '/images/blank_cover.png'); });</script>
    <script>$(document.location.hash).effect('highlight', 1500)</script>
  </section>
</div>